name: import_tracker_mtw
description: "A new Flutter project."
publish_to: 'none' # Elimina esta lÃ­nea si deseas publicar en pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpeg
    - assets/logo2.png
    - assets/pp.jpg
    - assets/pantalla_principal.png
